---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        class: "logging.Formatter"
        format: "%(asctime)s.%(msecs)03dZ %(levelname)s %(name)s filename:%(filename)s line(%(lineno)d) %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

root:
    level: INFO
    handlers: [console]
